version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Berlin"
    labels:
      - "githubactions"
      - "updates"
    open-pull-requests-limit: 5
