image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s ci-settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
cache:
  paths:
    - .m2/repository/
    - target/
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  needs:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  needs:
    - test
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
    - develop

pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean site:site site:stage-deploy -DstagingSiteURL=file://$(pwd)/public -DtopSiteURL=https://www.ds-2.de/
  artifacts:
    paths:
      - public
  only:
    - main
    - develop

# release:
#   stage: release
#   when:
#     - manual
#   rules:
#     - if: $CI_DEPLOY_FREEZE == null
#   needs:
#     - test
#   except:
#     - tags
#   script:
#     - mvn $MAVEN_CLI_OPTS release:clean release:prepare release:perform
#   only:
#     - releases/1.0
#   release:
#     name: "My awesome release"
#     tag_name: "v-$CI_COMMIT_TAG"
