image: maven:latest

include:
  - project: 'ds_2/ci-templates'
    ref: v0.1.19-alpha.3
    file: # you can add multiple files you need for your project
      - '/templates/stages.yaml'
      - '/templates/build-maven.yaml'
      - '/templates/release-marker.yaml'

variables:
  MAVEN_CLI_OPTS: "-s ci-settings.xml --batch-mode --errors --fail-at-end --show-version"

deploy:
  stage: release
  needs:
    - build-maven
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - develop

pages:
  stage: production
  script:
    - mvn $MAVEN_CLI_OPTS clean site:site site:stage-deploy -DstagingSiteURL=file://$(pwd)/public -DtopSiteURL=https://www.ds-2.de/
  artifacts:
    paths:
      - public
  only:
    - main
    - develop

release:
  stage: release
  script:
    - echo "Deploying tag $CI_COMMIT_TAG hopefully ;)"
    - mvn $MAVEN_CLI_OPTS clean deploy
  only:
    - tags
