name: build Site

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -s ci-settings.xml --batch-mode --update-snapshots clean site:site site:stage-deploy -DstagingSiteURL=file://$(pwd)/public -DtopSiteURL=https://www.ds-2.de/
        environment:
          CI_USERNAME: ${{secrets.CI_USERNAME}}
          CI_PASSWORD: ${{secrets.CI_PASSWORD}}
