name: build Site

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out current branch for this build
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: setup maven repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -s ci-settings.xml --batch-mode --update-snapshots clean site:site site:stage-deploy -DstagingSiteURL=file://$(pwd)/tmp -DtopSiteURL=https://www.ds-2.de/
        env:
          CI_USERNAME: ${{secrets.CI_USERNAME}}
          CI_PASSWORD: ${{secrets.CI_PASSWORD}}
      - name: copy to docs dir
        run: |
          mkdir -p docs || true
          cp -r tmp/file:/tmp/ds2-jee-bom-1.0.0-SNAPSHOT/* docs/
          find docs -maxdepth 2
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy to Artifactory
        run: mvn -s ci-settings.xml --batch-mode deploy
        env:
          CI_USERNAME: ${{secrets.CI_USERNAME}}
          CI_PASSWORD: ${{secrets.CI_PASSWORD}}
          CI_AZURE_STORAGEACC: ${{secrets.CI_AZURE_STORAGEACC}}
          CI_AZURE_SECKEY: ${{secrets.CI_AZURE_SECKEY}}
